// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadioDb.DataAccess;

#nullable disable

namespace StationListDb.Migrations
{
    [DbContext(typeof(StationDb))]
    [Migration("20220405164516_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("RadioDb.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CountryStations");
                });

            modelBuilder.Entity("RadioDb.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RawHtmlData");
                });

            modelBuilder.Entity("StationListDb.Models.StreamUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("StreamUrl");
                });

            modelBuilder.Entity("StationListDb.Models.StreamUrl", b =>
                {
                    b.HasOne("RadioDb.Models.Station", null)
                        .WithMany("Streams")
                        .HasForeignKey("StationId");
                });

            modelBuilder.Entity("RadioDb.Models.Station", b =>
                {
                    b.Navigation("Streams");
                });
#pragma warning restore 612, 618
        }
    }
}
